### PR TITLE
refactor(Scalar.AspNetCore): new structure, fluent API, better configuration coverage

### PR DESCRIPTION
**Pull request by xC0dex**
## Description

This PR refactors the entire AspNetCore solution. I think the new structure is easy to understand and common.

Relates to https://github.com/scalar/scalar/issues/1740.

### New project structure

To enhance clarity and maintainability, I've restructured the project as follows:

```
/src
  ├── /Scalar.AspNetCore
  │   ├── /Options
  │   │   ├── /Authentication  
  │   │   └── Option classes
  │   ├── /Extensions 
  │   └── /Enums
  │
/tests
  ├── /apis
  │   └── /Scalar.AspNetCore.Tests.Api
  └── /Scalar.AspNetCore.Tests
  │    └── test files 
  │    
/playground
  └── /Scalar.AspNetCore.Playground
      └── playground files
```
`Scalar.AspNetCore.Playground` is a playground project to get an instant feedback of changes in the library.

### Changes

In addition to restructuring, I’ve implemented standard naming conventions and made several improvements, including:

- Apply naming convention
- Refactored the code to make it cleaner and more readable.
- Add some useful properties to the project file
- Add a `.editorconfig` for coding conventions
- Add AOT support. I removed the usage of reflection and used source generated JSON serialization. Perhaps not need, but nice to have, as Microsoft's OpenAPI generator is also AOT friendly.
- Make `ScalarOptions` configurable via Options pattern (DI)
- Add a test project with tests for the endpoints and extension methods. (Current coverage is 83%)
- Provide extension methods for fluent configurable options.
- Add XML summaries/comments for all public members.
- Update the docs. It's not perfect, but I guess enough for the first iteration.

### Open questions

- I was thinking about a redirect from `/scalar` to `/scalar/v1`. However, this would require some changes in the endpoint configuration.
- Add GitHub workflows for build, test and publish. These flows _could_ be based on [ci.yml](https://github.com/xC0dex/APIWeaver/blob/main/.github/workflows/ci.yml) and [publish.yml](https://github.com/xC0dex/APIWeaver/blob/main/.github/workflows/publish.yml)

### JSON Configuration
I noticed that some properties aren't working as expected. The serialized configuration looks like this:
```json
{
  "proxy": "http://localhost:8080",
  "showSidebar": false,
  "hideModels": true,
  "hideDownloadButton": true,
  "hideTestRequestButton": true,
  "darkMode": false,
  "forceDarkModeState": "light",
  "hideDarkModeToggle": true,
  "customCss": "*{}",
  "searchHotKey": "o",
  "metadata": {
    "key": "value"
  },
  "defaultHttpClient": {
    "targetKey": "shell",
    "clientKey": "curl"
  },
  "hiddenClients": null,
  "authentication": {
    "preferredSecurityScheme": "my-scheme",
    "apiKey": {
      "token": "my-token"
    },
    "oAuth2": {
      "clientId": "my-client",
      "scopes": [
        "scope"
      ]
    }
  },
  "withDefaultFonts": false,
  "defaultOpenAllTags": true,
  "theme": "saturn"
}
```

Could someone verify if this looks correct?

### Breaking changes

The changes of `ScalarOptions` include breaking changes. E.g., in the last PR (https://github.com/scalar/scalar/pull/3007) the layout property was removed and I also renamed a property. I hope this is ok. From now on, we could mark existing properties as `[Obsolete]` before removing or renaming them.

I would love to contribute to `Scalar.AspNetCore` in the future 🥳.

### CODE REVIEW

**Comment by facus26** [comment]
The restructuring turned out great, and I agree that we could have some tests, even if they’re just a few lines.
It’s great that you added a testing layer; maybe we could also add support for .NET 8.
It was nice to be able to help with the project. #3007

**Comment by xC0dex** [comment]
Okay, as I never used Scalar before, I'm not 100% sure how the authentication part works. The current state in the `main` branch doesn't work because inheritance + `System.Text.Json` requires some additional configuration. My plan was to provide a fluent API like:
```c#
app.MapScalarApiReference(options =>
    {
        options
            .WithAuthentication(params)
            // or
            .WithApiKeyAuthentication(params)
    });
```

But it depends on how flexible the auth object is.

**Comment by xC0dex** [comment]
Hey @hanspagel,
I think it makes sense for me to "finish" the PR first before you give it a try. I'll set up a working playground for you. Currently, it's sometimes broken because it's still a work in progress and I'm experimenting with a few things 😆.

What are your thoughts on embedding the standalone JS file directly in the package, rather than relying on the one from the CDN? It's of course, possible to make this in a future iteration,

**Comment by hanspagel** [comment]
We’ve had this in other integrations and it caused more trouble than it helped. The current default for our integrations is: include the CDN (jsdelivr) and allow to overwrite the URL (to host it somewhere else or pin it to a specific version).

Here is our hono integration for example:

https://github.com/scalar/scalar/tree/main/packages/hono-api-reference#custom-cdn

**Comment by xC0dex** [comment]
@hanspagel, 

I believe it's now in a state where you can start experimenting with it to get a sense of how, for example, the fluent API works. I haven't added all the extension methods yet for every configuration, and some tests are still missing. Any kind of feedback is highly appreciated. I noticed that some configuration options don't work as expected, like the `HideDownloadButton`.
If you have any questions or need further clarification, please ask 😄.

IMO it's a quite nice solution so far.

**Comment by xC0dex** [comment]
Okay, I think the PR is finally ready for review 🎉. I've updated the description to reflect all changes in this PR.

**Comment by marclave** [comment]
this is AWESOME @xC0dex , had a quick question. how could i deploy this nuget now that we moved around some of the code :)

**Comment by xC0dex** [comment]
> this is AWESOME @xC0dex , had a quick question. how could i deploy this nuget now that we moved around some of the code :)

Thanks! You could do the following:

1. Navigate into the root folder of the project `packages/scalar.aspnetcore` and open a CLI.

2. Build the solution
```bash
dotnet build -c Release
```

3. Test the solution
```bash
dotnet test -c Release --no-build
```

4. Pack the main project
```bash
dotnet pack src/Scalar.AspNetCore -c Release --no-build --output package /p:Version=1.2.3
```
Now you should have the `.nupkg` file inside a newly created `package` folder.


Hopefully, we can automate these steps with a workflow soon.

**Review by marclave — APPROVED** [review]
lets ship it 😎

**Comment by xC0dex** [comment]
@marclave If anything related to AspNetCore package comes up, feel free to mention me there!

**Comment by marclave** [comment]
hey @xC0dex seems like im getting these test errors :) 

```

Test summary: total: 5, failed: 4, succeeded: 1, skipped: 0, duration: 0.8s
Build failed with 8 error(s) in 0.9s
marclaventure@marcbook scalar.aspnetcore % dotnet test -c Release --no-build

  Scalar.AspNetCore.Tests test failed with 8 error(s) (0.8s)
    /usr/local/share/dotnet/sdk/9.0.100-preview.4.24260.3/Microsoft.TestPlatform.targets(46,5): error : [xUnit.net 00:00:00.26]     Scalar.AspNetCore.Tests.ScalarEndpointTests.MapScalarApiReference_ShouldReturnIndex_WhenRequested [FAIL]
    /usr/local/share/dotnet/sdk/9.0.100-preview.4.24260.3/Microsoft.TestPlatform.targets(46,5): error : [xUnit.net 00:00:00.33]     Scalar.AspNetCore.Tests.ScalarEndpointTests.MapScalarApiReference_ShouldUseCustomCdn_WhenSpecified [FAIL]
    /usr/local/share/dotnet/sdk/9.0.100-preview.4.24260.3/Microsoft.TestPlatform.targets(46,5): error : [xUnit.net 00:00:00.35]     Scalar.AspNetCore.Tests.ScalarEndpointTests.MapScalarApiReference_ShouldReturnDefaultConfiguration_WhenNotSpecified [FAIL]
    /usr/local/share/dotnet/sdk/9.0.100-preview.4.24260.3/Microsoft.TestPlatform.targets(46,5): error : [xUnit.net 00:00:00.41]     Scalar.AspNetCore.Tests.ScalarEndpointTests.MapScalarApiReference_ShouldHandleCustom_WhenSpecified [FAIL]
    /Users/marclaventure/Software/scalar/packages/scalar.aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarEndpointTests.cs(37): error VSTEST1: Scalar.AspNetCore.Tests.ScalarEndpointTests.MapScalarApiReference_ShouldReturnIndex_WhenRequested: Scalar.AspNetCore.Tests.ScalarEndpointTests.MapScalarApiReference_ShouldReturnIndex_WhenRequested() Expected response.StatusCode to be HttpStatusCode.OK {value: 200}, but found HttpStatusCode.InternalServerError {value: 500}.
    /Users/marclaventure/Software/scalar/packages/scalar.aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarEndpointTests.cs(76): error VSTEST1: Scalar.AspNetCore.Tests.ScalarEndpointTests.MapScalarApiReference_ShouldUseCustomCdn_WhenSpecified: Scalar.AspNetCore.Tests.ScalarEndpointTests.MapScalarApiReference_ShouldUseCustomCdn_WhenSpecified() Expected response.StatusCode to be HttpStatusCode.OK {value: 200}, but found HttpStatusCode.InternalServerError {value: 500}.
    /Users/marclaventure/Software/scalar/packages/scalar.aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarEndpointTests.cs(54): error VSTEST1: Scalar.AspNetCore.Tests.ScalarEndpointTests.MapScalarApiReference_ShouldReturnDefaultConfiguration_WhenNotSpecified: Scalar.AspNetCore.Tests.ScalarEndpointTests.MapScalarApiReference_ShouldReturnDefaultConfiguration_WhenNotSpecified() Expected response.StatusCode to be HttpStatusCode.OK {value: 200}, but found HttpStatusCode.InternalServerError {value: 500}.
    /Users/marclaventure/Software/scalar/packages/scalar.aspnetcore/tests/Scalar.AspNetCore.Tests/ScalarEndpointTests.cs(97): error VSTEST1: Scalar.AspNetCore.Tests.ScalarEndpointTests.MapScalarApiReference_ShouldHandleCustom_WhenSpecified: Scalar.AspNetCore.Tests.ScalarEndpointTests.MapScalarApiReference_ShouldHandleCustom_WhenSpecified() Expected response.StatusCode to be HttpStatusCode.OK {value: 200}, but found HttpStatusCode.InternalServerError {value: 500}.

Test summary: total: 5, failed: 4, succeeded: 1, skipped: 0, duration: 0.8s
Build failed with 8 error(s) in 0.9s
marclaventure@marcbook scalar.aspnetcore % 
```

**Comment by xC0dex** [comment]
@marclave I'll check that!

**Comment by xC0dex** [comment]
@marclave They are working on my end. Maybe it's because you have preview 4 installed. The latest available SDK version is [preview 7](https://dotnet.microsoft.com/en-us/download/dotnet/9.0).

**Comment by marclave** [comment]
@xC0dex ah! ok :) we are so back

releasing now!

**Comment by xC0dex** [comment]
We need a workflow 🤣

**Comment by marclave** [comment]
@xC0dex omg we really do hahaah 🙃

**Comment by marclave** [comment]
its released, should be live soon ! https://www.nuget.org/packages/Scalar.AspNetCore/1.2.3#readme-body-tab

**Comment by facus26** [comment]
@xC0dex Excellent job!! Very good PR!

**Pull request merged**
