### PR TITLE
feat(api-client): display which auth is required on a request

### LINKED ISSUE #3613: Display which auth is required on which request
### What happens?

We currently allow users to select any auth on any request. However according to the spec, each request can specify its own security requirements. Instead of restricting the user to just those auth methods, we should show something in the UI that states which auth is required on which request without limiting the user

### PR DESCRIPTION
**Pull request by amritk**
closes #3613

image

@cameronrohani will replace the icon later

### CODE REVIEW

**Comment by amritk** [comment]
sorry @hwkr I just augmented ComboBox again instead of pulling it out 😳

**Comment by antlio** [comment]
great one! how would we feel about something like the following? always felt that it could be enhanced since i don't see a use case with twice the same auth would there be?
image

cc @cameronrohani

**Comment by cameronrohani** [comment]
> great one! how would we feel about something like the following? always felt that it could be enhanced since i don't see a use case with twice the same auth would there be? image
> 
> cc @cameronrohani

I like it @amritk, can we do this?

**Comment by amritk** [comment]
oh btw there will be 3 categories now: required auth, available auth, add new auth

**Comment by amritk** [comment]
Closing with a new one coming soon!

**Pull request closed without merging**
