### PR TITLE
refactor(api-client): codemirror usedropdown hook

### PR DESCRIPTION
**Pull request by antlio**
this pr favors useDropdown hook over code dropdown widget in order to have a better hand over the environment dropdown component, and fixes visibility on blur, and prepare to welcome the up down event in the dropdown.

image

### CODE REVIEW

**Review by marclave — APPROVED** [review]
i dig this :)

**Review by hanspagel — APPROVED** [review]
Cool

**Comment by hanspagel** [comment]
Blocked by #2931

**Comment by antlio** [comment]
> Blocked by #2931

I rebased it on it

**Pull request merged**
