### PR TITLE
feat(components): update combobox styles

### PR DESCRIPTION
**Pull request by hwkr**
Some small updates to the combobox styles based on how it would be used for request auth.

### CODE REVIEW

**Comment by cameronrohani** [comment]
Wow great work!

Should we add a placeholder - could just be "Search"

Also it seems like the search input is taking up too much vertical space - can we tighten that?

**Comment by cameronrohani** [comment]
Wow great work!

Should we add a placeholder - could just be "Search"

Also it seems like the search input is taking up too much vertical space - can we tighten that?

**Review by amritk — CHANGES_REQUESTED** [review]
I would remove all of the integration parts for now as auth is changing completely. Once we add multiple we can integrate

**Review by marclave — APPROVED** [review]

**Review by amritk — APPROVED** [review]
Send it

**Pull request merged**
