### PR TITLE
fix: remove editor tabs

### PR DESCRIPTION
**Pull request by marclave**
rolling back the editor interface to simplify things, we can in the future add the AI writer + tabs as slots :) 

image

### CODE REVIEW

**Review by geoffgscott — COMMENTED** [review]
We should move getting started to the references. Might also be good to slot the buttons while we are here. Could be done in a separate PR though

**Comment by marclave** [comment]
I'm happy to fast follow with that :)

**Comment by cameronrohani** [comment]
Awesome work, let's make sure we default to showing the getting started page on mobile:
image

Also let's make sure the buttons are spaced like how they were previously :) 
image

**Comment by marclave** [comment]
> Awesome work, let's make sure we default to showing the getting started page on mobile: image
> 
> Also let's make sure the buttons are spaced like how they were previously :) image

ah good idea, maybe we just remove the ai writer tab and just show the getting started tab on mobile?

**Comment by marclave** [comment]
closing in favor of https://github.com/scalar/scalar/pull/589

**Pull request closed without merging**
