### PR TITLE
style(components): updates modal animation

### PR DESCRIPTION
**Pull request by antlio**
this pr updates scalar modal animation to make it more consistent with the command palette in the client.

**before**

https://github.com/user-attachments/assets/c187c343-0cfa-481a-aefd-3d17ecb82da8

**after**

https://github.com/user-attachments/assets/3688cf77-20f4-4933-980d-de83333db8c3

### CODE REVIEW

**Comment by hanspagel** [comment]
I love it! Let’s see what @cameronrohani says

**Review by marclave — APPROVED** [review]

**Review by marclave — CHANGES_REQUESTED** [review]
oh actually @cameronrohani had a reason for not using transforms

**Comment by cameronrohani** [comment]
obviously this is preferred, i'm just always scared of adding transforms for those niche cases where windows users complain that the text inside is blurry 😿 

maybe we just don't do transforms on windows or something?

**Comment by antlio** [comment]
didn't we use it with command palette? @cameronrohani idea here is just for lack of consitency

**Review by marclave — APPROVED** [review]

**Comment by amritk** [comment]
> maybe we just don't do transforms on windows or something?

@cameronrohani don't forget windows is a big chunk of our audience! [(according to stackoverflow)](https://survey.stackoverflow.co/2024/technology#most-popular-technologies-op-sys)

**Pull request merged**
