### PR TITLE
chore(api-client): change Scalar API Client to Scalar

### PR DESCRIPTION
**Pull request by marclave**
drop the api client 😏

### CODE REVIEW

**Review by hanspagel — CHANGES_REQUESTED** [review]
There’s more that needs to be done I think. Did you search the repository for Scalar API Client?

**Comment by marclave** [comment]
just for the desktop app

**Comment by hanspagel** [comment]
Do it for client.scalar.com too!

**Comment by marclave** [comment]
naw for seo we should keep it

**Review by hanspagel — APPROVED** [review]

**Pull request merged**
