### PR TITLE
feat(components): add outline icons

### PR DESCRIPTION
**Pull request by hwkr**
Adds a number of new outline icons to be used in the Dashboard.

Google Chrome-2024-07-15-17-48-20@2x

It adds the following icons:

- House Icon
- Pencil Icon
- Google Icon

It also updates two icons:

1. The Link icon which isn't used anywhere (yet).
2. The Play icon which is now a line icon by default.

The Play icon can still have a fill added to it which I've done for all of the places we use it already. Video to make sure the Play icon is visually the same:

https://github.com/user-attachments/assets/58c443fc-8819-4691-8f2b-96d6c85feaad

### CODE REVIEW

**Review by geoffgscott — APPROVED** [review]
Looks good but are those style changes to client intentional?

**Comment by hwkr** [comment]
> Looks good but are those style changes to client intentional?

Yeah that's to account for the changes to the play icon

**Review by cameronrohani — CHANGES_REQUESTED** [review]
I think we were wanting to keep the play button filled to draw more attention to it, but other than that everything looks great!

**Review by cameronrohani — APPROVED** [review]
nvm saw the vid, great work

**Review by marclave — APPROVED** [review]

**Pull request merged**
