### PR TITLE
feat: add api client response empty state

### PR DESCRIPTION
**Pull request by antlio**
this pr introduces the response empty state ascii + style in the api client as seen below:

image

### CODE REVIEW

**Comment by hanspagel** [comment]
Alternative wording proposal:

“Fill the void and send your first request.”

probably needs a line break

**Comment by antlio** [comment]
> Alternative wording proposal:
> 
> “Fill the void and send your first request.”
> 
> probably needs a line break

love it! since that screen appears when we change endpoints, what about "Fill the void and send your request" as it might not be the first one?

**Comment by cameronrohani** [comment]
Awesome work! 😍

**Review by marclave — APPROVED** [review]
nothing empty about this state 😏 great work @antlio

**Pull request merged**
