### PR TITLE
style(themes): new selection colors

### PR DESCRIPTION
**Pull request by antlio**
big friday energy inspired by @JohnPhamous amazing [tweet](https://x.com/JohnPhamous/status/1770861726604419369). gave a first shot at our custom theme selection but feel free to play with it, as seen below:

<details>
<summary>alternate</summary>
image
image
</details>

<details>
<summary>default</summary>
image
image
</details>

<details>
<summary>moon</summary>
image
image
</details>

<details>
<summary>purple</summary>
image
image
</details>

<details>
<summary>solarized</summary>
image
image
</details>

<details>
<summary>blue planet</summary>
image
image
</details>

<details>
<summary>deep space</summary>
image
image
</details>

<details>
<summary>saturn</summary>
image
image
</details>

<details>
<summary>kepler 11e</summary>
image
image
</details>

<details>
<summary>mars</summary>
image
image
</details>

### CODE REVIEW

**Review by hwkr — APPROVED** [review]
Yoooo this looks awesome 🤩

**Comment by amritk** [comment]
Will give it the ✅ after @cameronrohani

**Review by hanspagel — APPROVED** [review]
Waiting for @cameronrohani to step up like

a cowboy

**Comment by cameronrohani** [comment]
do we need to put this in every single individual theme file or can we place it in the global theme?

@antlio

**Comment by antlio** [comment]
> do we need to put this in every single individual theme file or can we place it in the global theme?
> 
> @antlio

depends how we feel about this, for instance the mars theme requires some more contrast

**Review by hanspagel — APPROVED** [review]
So cool

**Pull request merged**
