### PR TITLE
feat: rebuild search modal

### PR DESCRIPTION
**Pull request by hwkr**
Google Chrome-2024-04-22-15-55-59@2x

### CODE REVIEW

**Comment by cameronrohani** [comment]
Great work! 

Can we do the following:
- add the icon for tags
- reduce vertical spacing to 6px instead of 10px on the anchor
- change gap from 4px -> 3px between the path and title?

**Comment by geoffgscott** [comment]
@marclave LGTM

**Comment by hwkr** [comment]
@cameronrohani 

* add the icon for tags - Done! Needed a hand from @marclave 
* reduce vertical spacing to 6px instead of 10px on the anchor - Done
* change gap from 4px -> 3px between the path and title? - Done

Google Chrome-2024-04-23-12-34-06@2x

**Comment by cameronrohani** [comment]
@marclave LGTM!

**Review by marclave — APPROVED** [review]
😮‍💨 unreal work @hwkr 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥

**Review by cameronrohani — APPROVED** [review]
great work!

**Review by marclave — APPROVED** [review]

**Pull request merged**
