### PR TITLE
feat(void-server): use common build tooling

### PR DESCRIPTION
**Pull request by geoffgscott**
Aligns void server with other builds. Also removes some dead packages

### CODE REVIEW

**Comment by hanspagel** [comment]
Thanks, highly appreciated! Let’s review and merge this on Tuesday, not before the big release today, I’d say. :v:

**Review by hanspagel — CHANGES_REQUESTED** [review]
I think something is off. The types and sourcemaps are in `dist/src/`.

Screenshot 2024-06-28 at 16 06 40

**Comment by geoffgscott** [comment]
> I think something is off. The types and sourcemaps are in `dist/src/`.
> 
> Screenshot 2024-06-28 at 16 06 40

package.json was included in the `tsconfig.build.ts` for some reason. Removed now.

**Review by hanspagel — APPROVED** [review]
Nice 🌟

**Review by marclave — APPROVED** [review]

**Pull request merged**
