### PR TITLE
chore: update to Vue 3.5

### PR DESCRIPTION
**Pull request by amritk**
- [x] needs thorough testing

### CODE REVIEW

**Comment by hanspagel** [comment]
Need to rebase on main, and make sure there’s no reactivity issues and such things with the new version.

**Review by hanspagel — APPROVED** [review]
I clicked around for a while and couldn’t find any issues. I think we should further test this in production. :)

**Comment by amritk** [comment]
There is a definite flash of content on the client, moving back to draft

**Comment by hanspagel** [comment]
I don't see it! How can I reproduce this?

**Comment by amritk** [comment]
> I don't see it! How can I reproduce this?

@hanspagel load up stripe or bigger spec and click around. I haven't looked for the cause yet

**Comment by hanspagel** [comment]
I don’t see it, can you make a screen recording or something? 👀

**Comment by amritk** [comment]
I did some testing on main and updated every package in api-client and it worked fine! I think previously I saw an unrelated issue.

@hanspagel I know you been keeping this PR up to date, but its really just changes in a few packages. I think we ditch it and open a new PR.

**Comment by amritk** [comment]
closing in favour of https://github.com/scalar/scalar/pull/3461

**Pull request closed without merging**
