### PR TITLE
fix: footer behind sidebar in footer below sidebar mode

### PR DESCRIPTION
**Pull request by hwkr**
https://github.com/scalar/scalar/assets/6374090/fb796b69-fe0a-4f1b-b8d5-ecc897bd1d7f

### CODE REVIEW

**Review by marclave — COMMENTED** [review]
nice fix @hwkr! did you link the packages to the org repo to make sure it doesnt impact it?

**Comment by hwkr** [comment]
> nice fix @hwkr! did you link the packages to the org repo to make sure it doesnt impact it?

Didn't get a chance to yet! Can do though

**Comment by hwkr** [comment]
IT WORKS
Google Chrome-2023-11-02-15-22-57@2x


The latest main here breaks the docs app when linked though

**Review by amritk — APPROVED** [review]
LGTM!

**Pull request merged**
