### PR TITLE
fix(api-client): adds request body input safety check

### PR DESCRIPTION
**Pull request by antlio**
this pr is part of #4214 in order to ensure the request body being displayed.

image

### CODE REVIEW

**Comment by hanspagel** [comment]
This is great! But why did the previous check fail?

**Comment by antlio** [comment]
> Quote reply

i don't find it
image

**Comment by hanspagel** [comment]
I mean, why was `v-show="activeRequest …`  not enough?

**Comment by antlio** [comment]
> I mean, why was `v-show="activeRequest …` not enough?

i'don't know i haven't been able to replicate that issue yet, this is preventing some logging error from poppin

**Pull request merged**
