### PR TITLE
feat: syntax highlighting for Markdown

### PR DESCRIPTION
**Pull request by hanspagel**
I saw a few specs with code blocks in their description. This PR adds syntax highlighting to the Markdown rendering. Languages are auto-detected.

Wdyt?

The theme definitely needs some love.

Screenshot 2023-10-17 at 16 20 01

### CODE REVIEW

**Review by marclave — COMMENTED** [review]
I love it! 

We probably want to interface with how we do the scalar theme-ing so users can customize this and it aligns with their scalar docs theme.

@cameronrohani thoughts?

**Comment by cameronrohani** [comment]
Looks great, we just need to use our colours (--default-theme-color-yellow, green, etc...) so it works across all themes

**Comment by hanspagel** [comment]
Awesome! Updated the scheme:

Screenshot 2023-10-18 at 22 10 52
Screenshot 2023-10-18 at 22 11 01
Screenshot 2023-10-18 at 22 10 46
Screenshot 2023-10-18 at 22 10 33
Screenshot 2023-10-18 at 22 10 26

**Review by marclave — APPROVED** [review]
awesome work @hanspagel , let's get this in after we sym link and test SSG :)

**Comment by hanspagel** [comment]
SSG works 🎉

**Pull request merged**
