### PR TITLE
feat(docusaurus): add showNavLink config option

### PR DESCRIPTION
**Pull request by mason-at-pieces**
**Problem**
Currently, there is no way to disable the nav links generated by the docusaurus plugin.

**Solution**
With this PR users can now choose to enable/disable the nav link for any spec file they add to their docs.

Default will stay as `true` but users can now simply set `showNavLinks` to false to remove the nav link

### CODE REVIEW

**Review by marclave — APPROVED** [review]
amazing @mason-at-pieces !!

code looks good, im about to test but could you add a changeset 

```
pnpm changeset
```

as a patch for docusaurus : )

**Comment by marclave** [comment]
tested and works great :)

**Comment by mason-at-pieces** [comment]
> as a patch for docusaurus : )

oh sorry, I did a minor instead of a patch. Whats the best way to fix this?

**Comment by marclave** [comment]
> > as a patch for docusaurus : )
> 
> oh sorry, I did a minor instead of a patch. Whats the best way to fix this?

i just renamed it to a patch :) lets merge it!

**Pull request merged**
