### PR TITLE
fix: remove empty content update

### PR DESCRIPTION
**Pull request by hwkr**
I don't know if this is important but it breaks a lot of stuff...

### CODE REVIEW

**Comment by amritk** [comment]
I agree, this thing was breaking standalone cdn references. But I'll leave to @hanspagel since he knows what its for

**Comment by hanspagel** [comment]
Yeah, without it, we’ll have duplicate content when switching between different documents. There’s probably a better way to reset the editor when switching documents, but I failed with a few different attempts (e.g. using Vue’s `key`).

It’s tough … :)

Can you describe the issues you’re seeing so I can test whatever solution we come up with against it?

**Comment by hwkr** [comment]
> Yeah, without it, we’ll have duplicate content when switching between different documents. There’s probably a better way to reset the editor when switching documents, but I failed with a few different attempts (e.g. using Vue’s `key`).
> 
> It’s tough … :)
> 
> Can you describe the issues you’re seeing so I can test whatever solution we come up with against it?

This causes the content to disappear whenever the hocuspocus config changes. For example in the app when you switch between guides and references the hocuspocus token gets updated and we lose the rendered content.

**Comment by hwkr** [comment]
@hanspagel I'm also not seeing any duplication when switching documents on this branch

https://github.com/scalar/scalar/assets/6374090/9651e717-d719-4279-b420-0690f0a31050

**Comment by hanspagel** [comment]
Yeah, let’s get this in! Hasn’t been a proper fixed and it seems it’s not even working. Thanks for finding this! 🤝

**Review by hanspagel — APPROVED** [review]

**Pull request merged**
