### PR TITLE
build(Scalar.AspNetCore): add ASP.NET Core build and test workflow

### PR DESCRIPTION
**Pull request by xC0dex**
### Description 

This PR adds a basic workflow for building, testing and publishing the `Scalar.AspNetCore` package.

### CODE REVIEW

**Comment by marclave** [comment]
oooo this is AWESOME @xC0dex !!!

okay so next steps:

- [ ]  i can add the appropriate api key to publish to https://www.nuget.org/packages/Scalar.AspNetCore
- [ ] we need to filter for the package and it being dependent @hanspagel ?
- [ ] 👀 anything else

**Comment by xC0dex** [comment]
I think this can be tricky to mix NuGet and NPM packages in a changeset 👀

**Comment by marclave** [comment]
> I think this can be tricky to mix NuGet and NPM packages in a changeset 👀

ah this is true! tbh i am quite the novice on release management 😅 but i love hitting the green button

@hanspagel can weigh in on best flow for that ✨

**Comment by xC0dex** [comment]
So from my understanding the `.changeset/config.json` needs to be extended by 

```json
"privatePackages": {
    "version": true,
    "tag": true
  }
```

In addition, inside the `scalar.aspnetcore` folder, we need a new package.json so changeset can track the package:

```json
{
  "name": "scalar.aspnetcore",
  "private": true,
  "version": "1.2.4"
}
```

So commands like `npx changeset` will now list the `scalar.aspnetcore` package.

However, currently, the publish command inside the `changesets/action@v1` action is

```bash
pnpm -r publish --access public
```

TBH, I don't know what this command is doing. But for the NuGet package, the command must be

```bash
dotnet pack -c Release --no-restore --output nupkgs /p:Version=$VERSION
```
to pack the project into a package and

```bash
dotnet nuget push nupkgs/*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
```
to publish it to nuget.org.

**Comment by hanspagel** [comment]
Great work!! For our Electron app, we’re hooking into the release process without actually publishing to npm, too.

1. The app has its own package.json:

https://github.com/scalar/scalar/blob/main/packages/api-client-app/package.json

2. We’re using `pnpm changeset` to create new changesets, and it’s tagging new version for dependency updates automatically.

3. It’s not publish to npm because of `private: true`.

4. CI requires those three things to actually trigger a release:

* The change must be in `main`
* The commit needs to start with `RELEASING:'`
* The package.json has to be modified

Here’s the actual GitHub Actions workflow:

https://github.com/scalar/scalar/blob/main/.github/workflows/ci.yml#L151-L195

We can totally copy that for the AspNet integration, without even changing the changeset config. :) Do you want me to add this, or do you want to do it? Awesome contribution (again)!

**Comment by xC0dex** [comment]
@hanspagel got it, thanks for the explanation! This looks like a good solution for the .NET package. I'll try to add a job tomorrow 👍. However, we have to parse the version number out of the `package.json` to use it during the pack and publish command.

**Comment by hanspagel** [comment]
Ah, that makes sense!

**Review by hanspagel — APPROVED** [review]
build + test looks good! 👏

**Comment by xC0dex** [comment]
Hey @hanspagel,

I've added a publishing job based on your recommended `todesktop-release` job. I made a dry-run (without the if conditions). Setup .NET, extracting version from `package.json` and pack works perfectly. Could you please re-review the PR? I don't know how to check if everything works as expected regarding the changeset 👀.

**Comment by marclave** [comment]
@xC0dex good news, i have sent the token to @hanspagel so hopefully we can get this merged today :)

**Comment by hanspagel** [comment]
Added a NUGET_TOKEN as a repository secret ✌️

**Comment by hanspagel** [comment]
There’s already 1.2.5 it seems, should we bump the version to be 1.2.5 in the package.json?

**Pull request merged**
