### PR TITLE
fix: stop rendering infinite child attributes

### PR DESCRIPTION
**Pull request by Amorim33**
fix: https://github.com/scalar/scalar/discussions/1049

## **Problem**
Currently, when defining a `Record` as part of a request body it is possible to infinitely show child attributes.

https://github.com/scalar/scalar/assets/42624869/05b35afb-5e00-49af-9523-78fb6b2f60a7

image

## **Explanation**
This happens because the `SchemaProperty` component does not check if the current value is an object before rendering a child `Schema` component. 

## **Solution**
With this PR the `SchemaProperty` is changed to only render a child schema when the current value is an object.

https://github.com/scalar/scalar/assets/42624869/f4cac496-8716-4d7e-a1c6-598bd48d3e0e

image

### CODE REVIEW

**Comment by Amorim33** [comment]
Sorry for not waiting for the discussion to become an issue.
Please, let me know if this aligns with the library's goals.🙏

**Comment by amritk** [comment]
hey @Amorim33 super thanks for the PR! Could you also provide the spec you were using to test?

**Comment by Amorim33** [comment]
> hey @Amorim33 super thanks for the PR! Could you also provide the spec you were using to test?

Just edited the hono api reference example😁

## OpenAPI
```json
{
    "info": {
        "title": "Example",
        "description": "The `@scalar/hono-api-reference` middleware renders a beautiful API reference based on your OpenAPI specification.",
        "version": "v1"
    },
    "openapi": "3.1.0",
    "components": {
        "schemas": {},
        "parameters": {}
    },
    "paths": {
        "/hello-world": {
            "get": {
                "description": "Respond a message",
                "tags": [
                    "basic example"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "message"
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        },
        "/posts": {
            "get": {
                "name": "Get all posts",
                "description": "Returns all posts",
                "tags": [
                    "posts"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "posts": {
                                            "type": "array",
                                            "items": {
                                                "type": "object",
                                                "properties": {
                                                    "id": {
                                                        "type": "number",
                                                        "default": 123
                                                    },
                                                    "title": {
                                                        "type": "string"
                                                    },
                                                    "body": {
                                                        "type": "string"
                                                    }
                                                },
                                                "required": [
                                                    "id",
                                                    "title",
                                                    "body"
                                                ]
                                            }
                                        }
                                    },
                                    "required": [
                                        "posts"
                                    ]
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "name": "Create post",
                "description": "Create a new post",
                "tags": [
                    "posts"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "title": {
                                        "type": "string",
                                        "default": "My Blog Post"
                                    },
                                    "recordStrings": {
                                        "type": "object",
                                        "additionalProperties": {
                                            "type": "string"
                                        }
                                    },
                                    "recordIntegers": {
                                        "type": "object",
                                        "additionalProperties": {
                                            "type": "number"
                                        }
                                    },
                                    "recordBooleans": {
                                        "type": "object",
                                        "additionalProperties": {
                                            "type": "boolean"
                                        }
                                    },
                                    "recordArrays": {
                                        "type": "object",
                                        "additionalProperties": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    },
                                    "recordRecords": {
                                        "type": "object",
                                        "additionalProperties": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    },
                                    "objectWithProperties": {
                                        "type": "object",
                                        "properties": {
                                            "id": {
                                                "type": "number",
                                                "default": 123
                                            },
                                            "title": {
                                                "type": "string",
                                                "default": "My Blog Post"
                                            }
                                        },
                                        "required": [
                                            "id",
                                            "title"
                                        ]
                                    }
                                },
                                "required": [
                                    "title",
                                    "recordStrings",
                                    "recordIntegers",
                                    "recordBooleans",
                                    "recordArrays",
                                    "recordRecords",
                                    "objectWithProperties"
                                ]
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "id": {
                                            "type": "number",
                                            "default": 123
                                        },
                                        "title": {
                                            "type": "string",
                                            "default": "My Blog Post"
                                        },
                                        "body": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    },
                                    "required": [
                                        "id",
                                        "title",
                                        "body"
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        },
        "/posts/{id}": {
            "delete": {
                "name": "Delete Post",
                "description": "Delete a post",
                "tags": [
                    "posts"
                ],
                "parameters": [
                    {
                        "schema": {
                            "type": "number",
                            "default": 123
                        },
                        "required": true,
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "status": {
                                            "type": "string",
                                            "default": "OK"
                                        },
                                        "message": {
                                            "type": "string",
                                            "default": "Post deleted"
                                        }
                                    },
                                    "required": [
                                        "status",
                                        "message"
                                    ]
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "status": {
                                            "type": "string",
                                            "default": "ERROR"
                                        },
                                        "message": {
                                            "type": "string",
                                            "default": "Post not found"
                                        }
                                    },
                                    "required": [
                                        "status",
                                        "message"
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by hanspagel** [comment]
Another great contribution, love it! 👏

**Review by hanspagel — APPROVED** [review]

**Pull request merged**
