### PR TITLE
fix(api-client): sidebar dragging

### PR DESCRIPTION
**Pull request by antlio**
this pr introduces the enableResizer prop for the sidebar component in order to only enable dragging / resizing on request view, and not on others like cookies, environments.

### CODE REVIEW

**Review by marclave — COMMENTED** [review]
vscode seems to keep the width different panes, wdyt about keeping it?

image
image

image

**Comment by cameronrohani** [comment]
@marclave I was thinking we should do this too :galaxy-brain:

**Comment by antlio** [comment]
because once shrinked its not openable anymore, but we could set a min width instead then on non request page?

**Comment by cameronrohani** [comment]
Yeah could work with min width I suppose! Let's do it? 😄

**Comment by antlio** [comment]
i ended up setting globally the sidebar width, while removing the drag and hide capability as it didn't feel seamless for now.

**Review by marclave — APPROVED** [review]
dig it :)

**Pull request merged**
