### PR TITLE
chore: move prettier rc to JSON

### PR DESCRIPTION
**Pull request by hwkr**

### CODE REVIEW

**Review by hanspagel — APPROVED** [review]
Omg thanks

**Comment by hanspagel** [comment]
Ah, CI is failing

**Comment by hwkr** [comment]
> Ah, CI is failing

Womp womp

**Review by amritk — CHANGES_REQUESTED** [review]
use mjs over json! It provides type safety

**Review by amritk — APPROVED** [review]
begrudgingly approved for vscode 😛

**Review by marclave — APPROVED** [review]
nice :)

**Pull request merged**
