### PR TITLE
Marc/fix missing property description

### PR DESCRIPTION
**Pull request by marclave**
this fixes https://github.com/scalar/scalar/issues/290 :)

### CODE REVIEW

**Review by cameronrohani — APPROVED** [review]
Good catch :)

**Comment by rajnandan1** [comment]
When will this go live

**Comment by marclave** [comment]
@rajnandan1 its going live in about 10 minutes :)

**Comment by marclave** [comment]
@rajnandan1 It should be live on the CDN now! Feel free to join the discord (https://discord.com/invite/8HeZcRGPFS) or email me (marc@scalar.com), or can open new tickets on GitHub if there are any other errors :)

**Pull request merged**
