### PR TITLE
chore: hoist workspace packages

### PR DESCRIPTION
**Pull request by tmastrom**
Hoist the following packages to the workspace level

tsc-alias
vite-node
vue-tsc
eslint
@typescript-eslint/eslint-plugin
tsconfig-paths
nodemon
ts-node

### CODE REVIEW

**Review by marclave — COMMENTED** [review]
i unfortunately am not the build person + have a bit of 🫨 from build stuff. 

so gunna let @geoffgscott @hanspagel @amritk test + validate this across all our packages +  testing in fresh installs of apps from stackblitz

**Review by geoffgscott — APPROVED** [review]
Looks good. @marclave This doesn't impact end packages as it's dev tooling hoisting only. It would fail if someone tried to use fork our workspace and use npm but I don't think that's a use case we care about.

**Comment by marclave** [comment]
> Looks good. @marclave This doesn't impact end packages as it's dev tooling hoisting only. It would fail if someone tried to use fork our workspace and use npm but I don't think that's a use case we care about.

cool can fix up the conflicts and we can get this in!

**Review by hanspagel — APPROVED** [review]
Yesss, it’s awesome. :) Thanks @tmastrom!

**Pull request merged**
