### PR TITLE
feat(api-reference): show response headers

### PR DESCRIPTION
**Pull request by hwkr**
Based on chats with Cam I added the response headers on the left in each response section. 

https://github.com/user-attachments/assets/17095e42-8a6f-4c8d-9b4c-5d47d703bc07

### CODE REVIEW

**Comment by cameronrohani** [comment]
this is looking awesome to me 😍 but we should get hans and marc's feedback on this


can we make the margins consistent here too 
image

**Comment by hanspagel** [comment]
LOVE THIS

**Review by hanspagel — APPROVED** [review]
Let’s fix the margins @cameronrohani mentioned and wait for @marclave feedback.

**Comment by hwkr** [comment]
Updated the margins! :) @cameronrohani 

Google Chrome-2024-09-06-13-05-21@2x

**Comment by hanspagel** [comment]
Look slick! Let’s get this in. If @marclave or @cameronrohani have additional feedback, we can ff with another PR. 😊

**Pull request merged**
