### PR TITLE
fix(hono-api-reference): move api-reference to devDependency

### PR DESCRIPTION
**Pull request by amritk**
We had included @scalar/api-reference as a dependency but the hono package actually uses the cdn standalone. This moves it to a devDependency for the types.

from #2649

### CODE REVIEW

**Review by marclave — APPROVED** [review]

**Comment by hanspagel** [comment]
Are we exposing the ReferenceConfiguration type though? Then we’d need to keep the package in the dependencies.

**Comment by amritk** [comment]
@hanspagel Ah you are right, but it doesn't make sense to add a giant dependency for just a type. Should we just copy paste it over?

Should we copy it over?

**Comment by hanspagel** [comment]
Yes, maybe we need `@scalar/types`, which could have the few types that we really want to expose and promote.

Sounds easier than it is though. Just as an example `ReferenceConfiguration` also includes other types like `AuthenticationState` and other complex stuff. :)

I’d like to work on it, but it’s still background processing in my mind.

**Comment by amritk** [comment]
Yea actually a lot of the types already exist inside of oas-utils including auth. we can just move them into scalar/types

**Comment by amritk** [comment]
Closed in favour of #2820

**Pull request closed without merging**
