### PR TITLE
chore: upgrade to TypeScript 5.6

### PR DESCRIPTION
**Pull request by amritk**
With every minor version, typescript gets smarter...

plus emoji imports

```typescript
import { "🍌" as banana } from "./foo"

/**
 * om nom nom
 */
function eat(food: string) {
    console.log("Eating", food);
};

eat(banana);
```

### CODE REVIEW

**Review by marclave — APPROVED** [review]

**Comment by amritk** [comment]
Going to put this one on hold. There was a bundle increase due to duplicated packages, so I tried deleting pnpm lock and it stopped working. No good!

**Comment by amritk** [comment]
Actually the issues were unrelated to this PR

**Comment by amritk** [comment]
re-opening this one as a draft

**Comment by hanspagel** [comment]
I wonder what could cause the bundle size increase. It might not be related to this PR though, sometimes it’s just inaccurate, I couldn’t really find out why. I’d say it shouldn’t stop us from upgrading TypeScript, though.

**Review by hanspagel — APPROVED** [review]

**Comment by amritk** [comment]
Awesome let's go

**Pull request merged**
