### PR TITLE
fix: remove useTemplateRef

### LINKED ISSUE #3859: [Vue warn] Set operation on key "value" failed: target is readonly.
I get the following warning when I run `pnpm dev` in packages/api-reference:

```
create-client.js:45 [Vue warn] Set operation on key "value" failed: target is readonly.
```

pointing to

```ts
// packages/api-client/src/libs/create-client.ts
  app.use(router)
  // Provide the workspace store for the useWorkspace hook
  app.provide('workspace', store)
  // Provide the layout for the useLayout hook
  app.provide('layout', layout)
```

What AI says: The error occurs because Vue 3's provide API creates a readonly reference by default to prevent child components from accidentally mutating provided values. In this case, the store object likely contains reactive properties that need to be mutable.

### PR DESCRIPTION
**Pull request by amritk**
This seems to cause issues when using the react integrations. Maybe hold off for a few versions

Closes #3859

### CODE REVIEW

**Comment by hwkr** [comment]
image

**Review by hwkr — APPROVED** [review]
image

**Comment by ja-plus** [comment]
usefull

**Comment by amritk** [comment]
@hwkr I think its time to bring it back!

**Pull request merged**
