### PR TITLE
fix: query params not added to request url

### PR DESCRIPTION
**Pull request by marclave**
**Problem**
No query params are sent to the proxy

**Explanation**
This happens because we dont add them to the url

**Solution**
With this PR we add them to the URL

### CODE REVIEW

**Review by amritk — APPROVED** [review]
we could use a regex as well, but if it works, it works!

**Review by hanspagel — CHANGES_REQUESTED** [review]
This is great !Test is failing, though. Didn’t look into it yet.

**Comment by hanspagel** [comment]
I think I fixed and improved it, but needs a re-review! @amritk @marclave

**Review by amritk — APPROVED** [review]
That is much better, nice work @hanspagel

**Pull request merged**
