### PR TITLE
feat: add basic golang proxy

### PR DESCRIPTION
**Pull request by marclave**

### CODE REVIEW

**Review by geoffgscott — APPROVED** [review]

**Comment by hanspagel** [comment]
Can we rebase and clean this up and just deploy it without even using it? Just to get this stale PR in. We can ff with the actual integration quickly.

**Comment by marclave** [comment]
> Can we rebase and clean this up and just deploy it without even using it? Just to get this stale PR in. We can ff with the actual integration quickly.

yeah let's do it! @geoffgscott i has to update the package.json commands to use go but not sure if you wanted to do smth different here

**Comment by Alifarmand** [comment]
Hey there gents! 
Any chance this PR is going to move forward?

**Comment by hanspagel** [comment]
Yessss! It’s top of our list for the next days. ✌️

**Comment by tmastrom** [comment]
Closing in favour of [1639](https://github.com/scalar/scalar/pull/1639)

**Comment by Alifarmand** [comment]
@marclave
Hey, 
I thought this PR was going to fix the issue of not showing a download link when an API returns a file. Maybe I was wrong, because that seems not to be fixed in the latest version after merge of 1639.

**Pull request closed without merging**
