### PR TITLE
feat(api-client): request sidebar context menu

### LINKED ISSUE #2702: delete workspaces
Currently, we can't delete workspaces! let's fix this

### PR DESCRIPTION
**Pull request by antlio**
this pr adds a new scalar context menu component and uses it:
- for the request sidebar item actions (rename, delete...)
- for the workspace actions (rename, delete)

this fixes #2702  as workspace can be removed unless it is the only existing one, in that case the button is disabled and a tooltip is displayed.

https://github.com/user-attachments/assets/8138d920-6452-4ef2-801a-d26de57c8380

### CODE REVIEW

**Comment by cameronrohani** [comment]
did the line height in the context menu get broken in this pr? the line height for the dropdown buttons should be 19.5px but i'm seeing 14.5px line height in the deploy preview

**Comment by antlio** [comment]
> did the line height in the context menu get broken in this pr? the line height for the dropdown buttons should be 19.5px but i'm seeing 14.5px line height in the deploy preview

good catch! will fix, still finishing it up to add the workspace deletion, pinging you for the final review!

**Review by cameronrohani — APPROVED** [review]

**Comment by antlio** [comment]
> lets get this into main once the conflicts are resolved!

let's goo

**Review by hanspagel — APPROVED** [review]

**Review by hanspagel — CHANGES_REQUESTED** [review]
I see the custom context menu only if I right-click on the request.
I see the native context menu when I click on the workspace.
I don't see any context menu when I click on drafts.

Is that how we want it? 🤔 I think I’d expect the custom context menu everywhere in the sidebar, just with different actions.

I’ve tested this: https://f7216cb0.client-980.pages.dev/

Screenshot 2024-08-08 at 12 49 33

Screenshot 2024-08-08 at 12 50 40

**Review by hanspagel — APPROVED** [review]

**Pull request merged**
