### PR TITLE
Fixed a couple typos :)

### PR DESCRIPTION
**Pull request by FotieMConstant**

### CODE REVIEW

**Review by marclave — DISMISSED** [review]
awesome @FotieMConstant ! thanks for fixing these typos :)

**Comment by marclave** [comment]
@FotieMConstant looks like you just have to run prettier on the markdown file :)

At the root of the repo, you should be able to `pnpm format`

**Comment by FotieMConstant** [comment]
> @FotieMConstant looks like you just have to run prettier on the markdown file :)
> 
> At the root of the repo, you should be able to `pnpm format`

Done!

**Comment by marclave** [comment]
@FotieMConstant looks like you merged main into your branch, I was wondering why there was 3k additions/removals.

Haha sorry but last thing is to just make sure your commit is there with it being formatted

**Comment by marclave** [comment]
@FotieMConstant looks like you merged main into your branch, I was wondering why there was 3k additions/removals.

 sorry but last thing is to just make sure your commit is there with it being formatted

**Comment by FotieMConstant** [comment]
> @FotieMConstant looks like you merged main into your branch, I was wondering why there was 3k additions/removals.
> 
> sorry but last thing is to just make sure your commit is there with it being formatted

everything looks good, just ran the format command again to double check the updates

**Comment by hanspagel** [comment]
Thanks for taking the time and submitting the changes! The merge commit would mess up the Git history too much, though. I’ve created a new PR with your commits here: #374

For the next PR I’d recommend to use `git rebase`. Read more about keeping PRs up to date: https://github.blog/changelog/2022-02-03-more-ways-to-keep-your-pull-request-branch-up-to-date/ ✌️

**Pull request closed without merging**
