### PR TITLE
feat: Add OAS utils package and package bootstrapping

### PR DESCRIPTION
**Pull request by geoffgscott**
We use many of these utils in different places. A separate package encapsulates the logic and dependencies in 1 place. This also prevents imports of simple functions from large packages.

### CODE REVIEW

**Comment by hanspagel** [comment]
Sorry, I’m on mobile and just skimmed through the changes just briefly, but some thoughts that popped up:

Why is that adding bun? Was that intentional? I think that would make contributing for windows users harder.

Most (or all?) OpenAPI related helper methods could live in the parser package.

Personally, I don’t like the name. We don’t use the OAS abbreviation anywhere else.

Thanks!

**Comment by geoffgscott** [comment]
@hanspagel I can pull bun. I like it for native TS execution but vite-node will work
I also agree we can migrate some more helper methods here
@marclave approved the package name. I am open to alternatives but I also don't think it matters much. `spec-utils` seemed too vague

**Review by marclave — APPROVED** [review]
nice :)

**Comment by amritk** [comment]
Once bundows is in we'll convert!!

**Pull request merged**
