### PR TITLE
feat: support OAuth2 authorization code flow

### PR DESCRIPTION
**Pull request by mpminardi**
**Problem**
Currently, the authorization code flow for oauth is not supported.

**Explanation**
This happens because support has not yet been built out.

**Solution**
With this PR the authorization code flow is now supported.

**Note**
This was built on top of https://github.com/scalar/scalar/pull/1949, ignore the first commit when reviewing.

### CODE REVIEW

**Comment by marclave** [comment]
@amritk is this in the new client?

**Comment by amritk** [comment]
Yep this is in the new one!

**Comment by marclave** [comment]
@mpminardi we really appreciate this pull request, we are sorry we couldnt get this one merged. it was almost the perfect storm as we were integrating our new API client.

Good news is we used a lot of this and your contribution is very much appreciated! this is live in the latest release of @scalar/api-reference :) 

please give it a spin ✨

**Comment by marclave** [comment]
https://github.com/scalar/scalar/pull/2302

**Comment by mpminardi** [comment]
> @mpminardi we really appreciate this pull request, we are sorry we couldnt get this one merged. it was almost the perfect storm as we were integrating our new API client.
> 
> Good news is we used a lot of this and your contribution is very much appreciated! this is live in the latest release of @scalar/api-reference :) 
> 
> please give it a spin ✨ 
> 
> https://github.com/scalar/scalar/pull/2302

No worries, and all good! Glad to hear it, will have to test things out 🙏

**Pull request closed without merging**
