### PR TITLE
feat(api-client): fix up and polish command palette

### PR DESCRIPTION
**Pull request by hwkr**
Started this PR to just clean up modals but ended up finding a bunch of global hotkey issues.

I moved the search and the command palette navigation hotkeys out of the global bus and onto the respective inputs. I'm not sure if there was a reason they needed to be global? I think those actions should only fire when their input is focused anyways and the global bus should be used for app wide hotkeys like CMD Enter, CMD K for the palette etc.

## Before / After

https://github.com/user-attachments/assets/78af75fc-fde0-4827-8943-5d5f8844dc41

### CODE REVIEW

**Comment by hanspagel** [comment]
What a great PR! We have to wait until #2931 is merged, though. 😵

**Review by hanspagel — APPROVED** [review]
Awesome! lgtm, @amritk wdyt?

**Comment by amritk** [comment]
Yup its the right play, just gunna rebase

**Review by amritk — APPROVED** [review]
Lets go!

**Pull request merged**
