### PR TITLE
fix(api-client): bottom navigation on mobile

### PR DESCRIPTION
**Pull request by hwkr**
https://github.com/user-attachments/assets/3feaa482-9776-412d-9788-9b5eeae10e5c

### CODE REVIEW

**Review by cameronrohani — APPROVED** [review]

**Comment by hanspagel** [comment]
THIS IS SO COOL

The preview on Cloudflare looks like this on my iPhone. Am I doing something wrong?

6673D956-F117-40F3-8DF6-0371170ABAEB_4_5005_c

**Comment by hwkr** [comment]
> THIS IS SO COOL
> 
> The preview on Cloudflare looks like this on my iPhone. Am I doing something wrong?
> 

Well that's not right, I'll have a look

**Comment by hwkr** [comment]
> THIS IS SO COOL
> 
> The preview on Cloudflare looks like this on my iPhone. Am I doing something wrong?
> 

Okay fixed!

**Comment by hwkr** [comment]
Also fixed an issue with dynamic viewport units and set the background for Safari iOS so it's actually dark under the notch.

IMG_6751

**Review by hanspagel — APPROVED** [review]
Looks so great on my iPhone, great improvement

**Pull request merged**
