### PR TITLE
fix(api-reference): missing servers

### PR DESCRIPTION
**Pull request by zer0npc**
**Problem**
The configuration of servers has no effect

### CODE REVIEW

**Review by marclave — COMMENTED** [review]
@zer0npc appreciate the PR and great fix :) wanna add a changeset and we can get this in? can be a patch :)

**Comment by zer0npc** [comment]
> @zer0npc appreciate the PR and great fix :) wanna add a changeset and we can get this in? can be a patch :)

Thanks for the review, i updated it

**Review by marclave — APPROVED** [review]

**Review by marclave — COMMENTED** [review]
@zer0npc i looked at the `Content` component and we dont take in a servers prop

```
const props = defineProps<{
  parsedSpec: Spec
  layout?: 'default' | 'accordion'
  baseServerURL?: string
  proxy?: string
}>()
```

what issue are you trying to solve @zer0npc ? :)

**Comment by zer0npc** [comment]
> @zer0npc i looked at the `Content` component and we dont take in a servers prop
> 
> ```
> const props = defineProps<{
>   parsedSpec: Spec
>   layout?: 'default' | 'accordion'
>   baseServerURL?: string
>   proxy?: string
> }>()
> ```
> 
> what issue are you trying to solve @zer0npc ? :)

It seems you have refactored servers and meger before 4 hours, but it has not been released yet. In the latest version 1.24.20, Content has servers props and it's not been passed in ApiReferenceLayout
[diff](https://github.com/scalar/scalar/pull/2245/files#diff-7841085ee0200f3e9e0109fce51f38c68ec1431bbee4d38ffcf4ff63ed39da2c)

**Comment by marclave** [comment]
> > @zer0npc i looked at the `Content` component and we dont take in a servers prop
> > ```
> > const props = defineProps<{
> >   parsedSpec: Spec
> >   layout?: 'default' | 'accordion'
> >   baseServerURL?: string
> >   proxy?: string
> > }>()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > what issue are you trying to solve @zer0npc ? :)
> 
> It seems you have refactored servers and meger before 4 hours, but it has not been released yet. In the latest version 1.24.20, Content has servers props and it's not been passed in ApiReferenceLayout [diff](https://github.com/scalar/scalar/pull/2245/files#diff-7841085ee0200f3e9e0109fce51f38c68ec1431bbee4d38ffcf4ff63ed39da2c)

😭 oh gosh my bad, yeah we are so so so so so close to integrating our new api client, sorry this got pushed back.

do you still hit this error on the latest release?

**Comment by zer0npc** [comment]
[https://github.com/scalar/scalar/blob/main/documentation/configuration.md#servers-server](https://github.com/scalar/scalar/blob/main/documentation/configuration.md#servers-server)
I used this. And i tried in latest release and it's still not working. I found that the configuration of servers has been ignored, `BaseUrl.vue` only read OpenAPI spec now.

**Comment by hanspagel** [comment]
Oh man, you’re so right. This just got lost in the refactoring. I’ve submitted a fresh PR: #2306. ✌️

**Pull request closed without merging**
