### PR TITLE
feat(components): scalar icon loading placeholder

### PR DESCRIPTION
**Pull request by antlio**
this pr updates scalar icon component to introduce a loading placeholder.

### CODE REVIEW

**Review by hwkr — APPROVED** [review]
Looks good to me!

**Comment by marclave** [comment]
@antlio wanna show a preview plz and ty ✨

**Comment by antlio** [comment]
i don't think this changed what was intended here, will give another try

**Comment by amritk** [comment]
I got a fix for the flickering. Just rotate the container instead of the icon. Why it works I don't know

**Review by marclave — APPROVED** [review]

**Comment by antlio** [comment]
> I got a fix for the flickering. Just rotate the container instead of the icon. Why it works I don't know

will 👁️ that up! 🙏

**Pull request merged**
