### PR TITLE
fix: storybook script update

### PR DESCRIPTION
**Pull request by antlio**
this pr is a proposal to update script regarding storybook in order to be able to access components on the fly from this page:

image

### CODE REVIEW

**Comment by hwkr** [comment]
This won't work for `https://scalar-deploy-preview.netlify.app/` though right?

**Comment by antlio** [comment]
> This won't work for `https://scalar-deploy-preview.netlify.app/` though right?

nope only locally, might need help from @tmastrom for that matter

**Review by hwkr — APPROVED** [review]
lgtm!!

**Review by tmastrom — APPROVED** [review]
Nice quality of life update

**Review by marclave — APPROVED** [review]
nice 😎 defs helpful there to have it readily avail!

**Pull request merged**
