### PR TITLE
chore(scalar-app): rename app folder

### PR DESCRIPTION
**Pull request by hanspagel**
We’re talking about the _Scalar App_ most of the time, so I think it’s time to streamline the naming here:

* Rename `packages/api-client-app` to `packages/scalar-app`
* Rename the package from `scalar-api-client` to `scalar-app`.

### CODE REVIEW

**Comment by amritk** [comment]
We can rename the app, but I'm not sure I agree with the package. It should still be client while we have references and client so they can be easily distinguished

**Comment by amritk** [comment]
oh whats scalar-api-client lol

**Review by amritk — APPROVED** [review]

**Review by tmastrom — COMMENTED** [review]
An argument could be made for `scalar-desktop` too but I think this works

**Pull request merged**
