### PR TITLE
feat(api-reference): allow to hide search

### PR DESCRIPTION
**Pull request by antlio**
This PR is a proposal to introduce the `hideSearch` option to allow users to hide the search from api reference sidebar as requested in #2869.

**Preview**

```js
{
  hideSearch: true
}
```

image

### CODE REVIEW

**Review by hanspagel — COMMENTED** [review]
Should it hide the search in the client, too? 🤔 And do we need to disable the keyboard shortcut to?

**Comment by antlio** [comment]
> Should it hide the search in the client, too? 🤔 And do we need to disable the keyboard shortcut to?

no strong opinion, but i guess we could do it there too 

oops initially disabled the modal but i guess i removed it, will add again!

**Comment by marclave** [comment]
> Should it hide the search in the client, too? 🤔 And do we need to disable the keyboard shortcut to?

we can keep search in the api client, cause that search is more of a filter : )

**Comment by antlio** [comment]
> > Should it hide the search in the client, too? 🤔 And do we need to disable the keyboard shortcut to?
> 
> we can keep search in the api client, cause that search is more of a filter : )

should be good to go then

**Review by marclave — APPROVED** [review]

**Pull request merged**
