### PR TITLE
chore: add `default` to package.json exports fields

### LINKED ISSUE #2994: No "exports" main defined
When using the `@scalar/hono-api-reference` with tsx it seems to throw the following error:

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /node_modules/@scalar/hono-api-reference/package.json

More context: #2993

### PR DESCRIPTION
**Pull request by geoffgscott**
Adds fallback exports for require syntax

closes #2994

### CODE REVIEW

**Review by amritk — APPROVED** [review]
Quick work!

**Comment by hanspagel** [comment]
Pls let me review this, too. Seems easy, but just because it affects many packages.

**Review by tmastrom — APPROVED** [review]
LGTM

**Review by hanspagel — APPROVED** [review]
Looks good! :)

**Pull request merged**
