### PR TITLE
fix(api-client): sidebar fixtures

### PR DESCRIPTION
**Pull request by antlio**
this pr fixes:
- sidebar width issue with long request name
- address bar font size consistency
- sidebar search background fade
- delete modal request name length

image

### CODE REVIEW

**Comment by hanspagel** [comment]
Still pretty big, eh? Shouldn’t we limit this to three lines or so?

Screenshot 2024-09-19 at 10 34 33

**Comment by antlio** [comment]
> Still pretty big, eh? Shouldn’t we limit this to three lines or so?
> 

decreased to 3 ✔️

**Review by tmastrom — COMMENTED** [review]
Nice! 

Screenshot 2024-09-19 at 1 51 01 PM

Can we also limit Workspace name display length?

**Comment by antlio** [comment]
> Nice!
> 
> Can we also limit Workspace name display length?

great catch

image

**Review by hanspagel — APPROVED** [review]
Nice

**Review by amritk — APPROVED** [review]
Nice work!

**Pull request merged**
