### PR TITLE
style(api-client): layout responsiveness

### PR DESCRIPTION
**Pull request by antlio**
this pr updates layout responsiveness to reach a good enough on mobile, to be enhanced later on:

**before**
image

**after**
image

### CODE REVIEW

**Review by hanspagel — APPROVED** [review]
Pragmatic solution, love it!

**Comment by amritk** [comment]
were we going to get rid of the path nesting @marclave ?

**Review by hwkr — APPROVED** [review]
Looks good to me!

**Comment by hanspagel** [comment]
Let’s wait for #2931 here, too. 🧘

**Pull request merged**
