### PR TITLE
feat(scalar.aspnetcore): add integration configuration property

### PR DESCRIPTION
**Pull request by xC0dex**
## Description

This PR adds the `_integration` property to the configuration. The .NET integration provides a new `DotNetFlag` property, which is set to `true` by default.

### CODE REVIEW

**Review by hanspagel — APPROVED** [review]
expose framework! that’s a great name for it. Thanks for helping me out here! 👏 

ah, we said expose sounds more dangerous than it has to be. ok, let me think about it.

**Comment by xC0dex** [comment]
> ah, we said expose sounds more dangerous than it has to be. ok, let me think about it.

What about `ShowFramework`? We could also consider making this not configurable 🤣.

**Comment by marclave** [comment]
@xC0dex awesome! happy to merge as soon as you're good to go : )

**Comment by marclave** [comment]
waiting on @hanspagel based on @xC0dex conversation

> Hans want to think about an alternative property name

**Comment by marclave** [comment]
> Maybe the property could be named `DotnetFlag` and the extension `WithDotnetFlag`. A nice explanation could describe what this property is used for.

yeah lets do that!

**Comment by hanspagel** [comment]
Yes, that sounds great! But wouldn’t it be DotNet (with a big N)?

**Comment by xC0dex** [comment]
I'll rename it later this day.

**Comment by xC0dex** [comment]
Renamed to `DotNetFlag`. Hit the green button 🚀!

**Comment by marclave** [comment]
@xC0dex my all time fav button

**Pull request merged**
