### PR TITLE
feat: Add new configuration options and docs

### PR DESCRIPTION
**Pull request by facus26**
Some missing configurations have been added to the AspNetCore SDK, and documentation has been updated.

**Added options:** 
- HideModels
- ForceDarkModeState
- HideDarkModeToggle
- DefaultOpenAllTags
- DefaultHttpClient
- HiddenClients - Left as a bool for easier configuration.

**New Features:** 
- **EnabledClients** and **EnabledTargets**: Allow filtering ONLY the ones you want to show. These options override the HiddenClients array with the opposite options.
- **Authentication**: Improved class relationships.
- **Theme**, **Clients** and **Targets** are available as enum options.
- Add documentation options

### CODE REVIEW

**Review by marclave — APPROVED** [review]
🤯 LETS GO @facus26 

awesome work :)

**Comment by marclave** [comment]
i'll merge and do a release :)

**Comment by xC0dex** [comment]
Hey @facus26 @marclave,
nice work 🚀! I was planning to do a similar PR 🤣. I have one small suggestion: I would prefer using the `PascalCase` naming convention for enum members instead of `SCREAMING_SNAKE_CASE`. I just wanted to leave this feedback here before the release, as changing this afterward could result in a breaking change.

**Comment by facus26** [comment]
Hi @xC0dex!
I think it’s an excellent idea to standardize the names that way. Will you make the change?

**Comment by facus26** [comment]
I can wait; I don’t know when this release will be published.

**Comment by xC0dex** [comment]
@facus26 I'll drop a Draft PR soon, then we can discuss everything there, ok?

**Comment by xC0dex** [comment]
Here is the PR: https://github.com/scalar/scalar/pull/3019

**Pull request merged**
